#DEFINE CRLF CHR(13)+CHR(10)

//HTTP
#DEFINE HEADER_DELIMITER chr(13)+chr(10)+chr(13)+chr(10)

//SMTP
#DEFINE INTERNAL_DELIMITER ";"
#DEFINE INTERNAL_SEPARATORS ","

//SMTP Languages
#DEFINE language "EN"
#IF language == "FR" && French
	#DEFINE MSG_ERR_UNABLE_INTIALIZE_WS  "ERR00 : Impossible d'initialiser Winsock sur cette machine."
	#DEFINE MSG_ERR01_MISSING_SMTP_HOST  "ERR01 : Précisez le serveur SMTP dans la propriété SMTP_HOST."
	#DEFINE MSG_ERR02_MISSING_FROM       "ERR02 : Précisez le mail de l'expéditeur dans la propriété FROM."
	#DEFINE MSG_ERR03_MISSING_TO         "ERR03 : Précisez le mail du destinataire dans la propriété TO."
	#DEFINE MSG_ERR04_UNREACHABLE_HOST   "ERR04 : Impossible de se connecter au serveur."
	#DEFINE MSG_ERR05_NOREPLY_HOST       "ERR05 : Pas de réponse du serveur"
	#DEFINE MSG_ERR06_FILE_NOFOUND       "ERR06 : Le fichier à attacher n'existe pas."
	#DEFINE MSG_ERR07_MHTML_FILE_NOFOUND "ERR07 : Le fichier mhtml servant pour le message n'existe pas."
	#DEFINE MSG_ERR08_MHTML_FILE_WRONG   "ERR08 : Le fichier mhtml indiqué ne semble pas être au format mhtml (archive web). Il ne contient pas de MIME-Version."
	#DEFINE MSG_ERR09_WRONG_RESPONSE     "ERR09 : Le retour attendu était :"
	#DEFINE MSG_ERR10_CONNECT_LOST       "ERR10 : XXX connexion serveur SMTP perdue."
	#DEFINE MSG_ERR14_SENDDATA_RETRY     "ERR14 : Nouvel Essai... Nombre de caractères :"
	#DEFINE MSG_ERR15_SENDDATA_TIMEOUT   "ERR15 : Erreur de Timeout dans l'exécution de SendData."
	#DEFINE MSG_ERR16_EMAIL_REJECTED     "ERR16 : Adresse Email Rejetée."
	#DEFINE MSG_ERR17_MESSAGE_REJECTED   "ERR17 : Message refusé."
#ELIF language == "PL" && Polish
	#DEFINE MSG_ERR_UNABLE_INTIALIZE_WS  "ERR00 : Nie mo¿na zainicjowaæ us³ugi Winsock na tym komputerze."
	#DEFINE MSG_ERR01_MISSING_SMTP_HOST  "ERR01 : Okreœl serwer SMTP we w³aœciwoœci SMTP_HOST. "
	#DEFINE MSG_ERR02_MISSING_FROM       "ERR02 : Okreœl adres pocztowy nadawcy we w³aœciwoœci FROM."
	#DEFINE MSG_ERR03_MISSING_TO         "ERR03 : Okreœl adres pocztowy odbiorcy we w³aœciwoœci TO."
	#DEFINE MSG_ERR04_UNREACHABLE_HOST   "ERR04 : Serwer poczty nieosi¹galny."
	#DEFINE MSG_ERR05_NOREPLY_HOST       "ERR05 : Brak odpowiedzi ze strony serwera."
	#DEFINE MSG_ERR06_FILE_NOFOUND       "ERR06 : Nie znaleziono pliku za³¹cznika."
	#DEFINE MSG_ERR07_MHTML_FILE_NOFOUND "ERR07 : Nie znaleziono pliku za³¹cznika mhtml."
	#DEFINE MSG_ERR08_MHTML_FILE_WRONG   "ERR08 : Plik mhtml wydaje siê byæ w nieprawid³owym formacie. Nie zawiera MIME-Version"
	#DEFINE MSG_ERR09_WRONG_RESPONSE     "ERR09 : Oczekujê na odpowiedŸ z: "
	#DEFINE MSG_ERR10_CONNECT_LOST       "ERR10 : XXX utracone po³¹czenie z serwerem SMTP."
	#DEFINE MSG_ERR14_SENDDATA_RETRY     "ERR14 : Ponawiam próbê wys³ania danych ... Liczba bajtów: "
	#DEFINE MSG_ERR15_SENDDATA_TIMEOUT   "ERR15 : B³¹d limitu czasu podczas wykonania SendData."
	#DEFINE MSG_ERR16_EMAIL_REJECTED     "ERR16 : Email Address Rejected."
	#DEFINE MSG_ERR17_MESSAGE_REJECTED   "ERR17 : Message Rejected."
#ELIF language == "CZ" && Czech
	#DEFINE MSG_ERR_UNABLE_INTIALIZE_WS  "ERR00 : Chyba incializace knihovny Winsock."
	#DEFINE MSG_ERR01_MISSING_SMTP_HOST  "ERR01 : Zadejte SMTP server v parametru SMTP_HOST."
	#DEFINE MSG_ERR02_MISSING_FROM       "ERR02 : Zadejte adresu odesilatele v parametru FROM."
	#DEFINE MSG_ERR03_MISSING_TO         "ERR03 : Zadejte adresu pøíjemce v parametru TO."
	#DEFINE MSG_ERR04_UNREACHABLE_HOST   "ERR04 : Mail server není dostupný."
	#DEFINE MSG_ERR05_NOREPLY_HOST       "ERR05 : Server neodpovídá."
	#DEFINE MSG_ERR06_FILE_NOFOUND       "ERR06 : Soubor s pøílohou nenalezen."
	#DEFINE MSG_ERR07_MHTML_FILE_NOFOUND "ERR07 : Soubor s pøílohou mhtml nenalezen."
	#DEFINE MSG_ERR08_MHTML_FILE_WRONG   "ERR08 : Soubor mhtml neobsahuje MIME-Version. Soubor pravdìodobnì není ve formátu mhtml."
	#DEFINE MSG_ERR09_WRONG_RESPONSE     "ERR09 : Oèekávaná návratová hodnota: "
	#DEFINE MSG_ERR10_CONNECT_LOST       "ERR10 : XXX spojení se SMTP serverem pøerušeno."
	#DEFINE MSG_ERR14_SENDDATA_RETRY     "ERR14 : Opakuji odesílání dat... Celkem Bytù:"
	#DEFINE MSG_ERR15_SENDDATA_TIMEOUT   "ERR15 : Èasový limit pro SendData vypršel."
	#DEFINE MSG_ERR16_EMAIL_REJECTED     "ERR16 : Emailová adresa odmítnuta."
	#DEFINE MSG_ERR17_MESSAGE_REJECTED   "ERR17 : Message Rejected."
#ELIF language == "NL" && Dutch
	#DEFINE MSG_ERR_UNABLE_INTIALIZE_WS  "ERR00 : Kan Winsoch op deze pc niet initialiseren."
	#DEFINE MSG_ERR01_MISSING_SMTP_HOST  "ERR01 : SMTP server is niet opgegeven."
	#DEFINE MSG_ERR02_MISSING_FROM       "ERR02 : Afzender mail is niet opgegeven in FROM property."
	#DEFINE MSG_ERR03_MISSING_TO         "ERR03 : Ontvanger mail is niet opgegeven in TO property."
	#DEFINE MSG_ERR04_UNREACHABLE_HOST   "ERR04 : Server niet bereikbaar."
	#DEFINE MSG_ERR05_NOREPLY_HOST       "ERR05 : Geen reactie van server ontvangen"
	#DEFINE MSG_ERR06_FILE_NOFOUND       "ERR06 : Bijlage kan niet gevonden worden."
	#DEFINE MSG_ERR07_MHTML_FILE_NOFOUND "ERR07 : MHTML bijlage kan niet gevonden worden."
	#DEFINE MSG_ERR08_MHTML_FILE_WRONG   "ERR08 : Het MHTML bestand is niet in het juiste formaat. Er is geen MIME-versie aanwezig."
	#DEFINE MSG_ERR09_WRONG_RESPONSE     "ERR09 : Verwacht antwoord was :"
	#DEFINE MSG_ERR10_CONNECT_LOST       "ERR10 : XXX verbinding verbroken met SMTP server."
	#DEFINE MSG_ERR14_SENDDATA_RETRY     "ERR14 : nogmaals proberen gegevens te versturen....Aantal Bytes:"
	#DEFINE MSG_ERR15_SENDDATA_TIMEOUT   "ERR15 : Timeout fout op server."
	#DEFINE MSG_ERR16_EMAIL_REJECTED     "ERR16 : Emailadres afgekeurd."
	#DEFINE MSG_ERR17_MESSAGE_REJECTED   "ERR17 : Message Rejected."
#ELIF language == "IT" && Italiano
	#DEFINE MSG_ERR_UNABLE_INTIALIZE_WS  "ERR00 : Impossibile inizializzare Winsock su questo computer."
	#DEFINE MSG_ERR01_MISSING_SMTP_HOST  "ERR01 : Specificare il server SMTP nella proprietà SMTP_HOST."
	#DEFINE MSG_ERR02_MISSING_FROM       "ERR02 : Specificare il mittente nella proprietà FROM."
	#DEFINE MSG_ERR03_MISSING_TO         "ERR03 : Specificare il destinatario nella proprietà TO."
	#DEFINE MSG_ERR04_UNREACHABLE_HOST   "ERR04 : Server non raggiungibile."
	#DEFINE MSG_ERR05_NOREPLY_HOST       "ERR05 : Nessuna risposta dal server."
	#DEFINE MSG_ERR06_FILE_NOFOUND       "ERR06 : File allegato non trovato."
	#DEFINE MSG_ERR07_MHTML_FILE_NOFOUND "ERR07 : File mhtml allegato non trovato."
	#DEFINE MSG_ERR08_MHTML_FILE_WRONG   "ERR08 : il file mhtml non sembra essere nel formato corretto. Non contiene MIME-Version."
	#DEFINE MSG_ERR09_WRONG_RESPONSE     "ERR09 : La risposta attesa era :"
	#DEFINE MSG_ERR10_CONNECT_LOST       "ERR10 : XXX la connessione con il server SMTP è caduta."
	#DEFINE MSG_ERR14_SENDDATA_RETRY     "ERR14 : nuovo tentativo di spedizione... Numero di Bytes:"
	#DEFINE MSG_ERR15_SENDDATA_TIMEOUT   "ERR15 : Errore di Timeout in SendData."
	#DEFINE MSG_ERR16_EMAIL_REJECTED     "ERR16 : Indirizzo Email rifiutato."
	#DEFINE MSG_ERR17_MESSAGE_REJECTED   "ERR17 : Messaggio rifiutato."
#ELSE  && English
	#DEFINE MSG_ERR_UNABLE_INTIALIZE_WS  "ERR00 : Unable to initialize Winsock on This computer."
	#DEFINE MSG_ERR01_MISSING_SMTP_HOST  "ERR01 : Specify the SMTP server in SMTP_HOST property."
	#DEFINE MSG_ERR02_MISSING_FROM       "ERR02 : Specify the mail sender in FROM property."
	#DEFINE MSG_ERR03_MISSING_TO         "ERR03 : Specify the mail recipient in TO property."
	#DEFINE MSG_ERR04_UNREACHABLE_HOST   "ERR04 : Server unreachable."
	#DEFINE MSG_ERR05_NOREPLY_HOST       "ERR05 : No response from the server"
	#DEFINE MSG_ERR06_FILE_NOFOUND       "ERR06 : attachment file not found."
	#DEFINE MSG_ERR07_MHTML_FILE_NOFOUND "ERR07 : mhtml attachment file not found."
	#DEFINE MSG_ERR08_MHTML_FILE_WRONG   "ERR08 : The mhtml file does not seem to be in mhtml format. It does not contain a MIME-Version."
	#DEFINE MSG_ERR09_WRONG_RESPONSE     "ERR09 : Expected return was :"
	#DEFINE MSG_ERR10_CONNECT_LOST       "ERR10 : XXX connection lost with SMTP server."
	#DEFINE MSG_ERR14_SENDDATA_RETRY     "ERR14 : retry send data... Number of Bytes:"
	#DEFINE MSG_ERR15_SENDDATA_TIMEOUT   "ERR15 : Timeout error in SendData."
	#DEFINE MSG_ERR16_EMAIL_REJECTED     "ERR16 : Email Address Rejected."
	#DEFINE MSG_ERR17_MESSAGE_REJECTED   "ERR17 : Message Rejected."
#ENDIF

//SOCKETWRENCH
#DEFINE USEFREEVERSION
#DEFINE CSWSOCK_CONTROL			"SocketTools.SocketWrench.6"

//SocketWrench 8
//#DEFINE CSWSOCK_CONTROL			"SocketTools.SocketWrench.8"
//#DEFINE CSWSOCK_LICENSE_KEY		"INSERT YOUR RUNTIME LICENSE HERE"

//SocketWrench 9
//#DEFINE CSWSOCK_CONTROL			"SocketTools.SocketWrench.9"
//#DEFINE CSWSOCK_LICENSE_KEY		"INSERT YOUR RUNTIME LICENSE HERE"